---
run:
  concurrency: 6
  deadline: 5m
  skip-dirs-use-default: true
  skip-dirs:
    - contrib
    - dependencies
  skip-files:
    - swagger.go
  modules-download-mode: readonly
linters:
  enable-all: true
  disable:
    # All these break for one reason or another
    - nolintlint # some linter must be disabled (see `nolint` in the code)
    - tagliatelle # too many JSON keys cannot be changed due to compat
    - gocognit
    - testpackage
    - goerr113
    - exhaustivestruct
    - errorlint
    - wrapcheck
    - paralleltest
    - wsl
    - godox
    - tparallel
    - gomnd
    - nlreturn
    - noctx
    - nestif
    - predeclared
    - thelper
    - ifshort
    - staticcheck
    - forbidigo
    - exhaustive
    - unparam
    - gofumpt
    - gci
    - godot
    - dupl
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocyclo
    - lll
    - unconvert
    - errcheck
    - gocritic
    - gosec
    - maligned
    - gomoddirectives
    - revive
    - containedctx
    - contextcheck
    - cyclop
    - errname
    - forcetypeassert
    - ireturn
    - varnamelen
    - maintidx
    - nilnil
linters-settings:
  errcheck:
    check-blank: false
    ignore: encoding/json:^Unmarshal,fmt:.*
