# Upstream: github.com/tzkhan/pr-update-action

name: "PR title check"

on:
  pull_request_target:
    branches:
      - "!master"   # causes errors; reason unknown

jobs:
  update_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: tzkhan/pr-update-action@bbd4c9395df8a9c4ef075b8b7fe29f2ca76cdca9 # v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        base-branch-regex: '^(?!master).*$'
        title-template: '[%basebranch%]'
        title-prefix-space: true
